### ISSUE TITLE
Remove dependency on docker-compose

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/sbtc-bridge-web#103]
Docker compose can be removed completely since mongo-db has been moved out to Mongo Cloud and there is now only a single docker container running for the Bridge API.

Note: this issue impacts bridge web via build & deployment files.

**Comment by igorsyl** [comment]
Let's keep the docker compose file as it is a useful artifact for deployment to k8s.

**Comment by igorsyl** [comment]
I still use the docker compose to generate k8s help to deploy API to K8s. Had some trouble deploying to Google Run.

**Comment by radicleart** [comment]
This PR splits the API into two separate containers supporting testnet and mainnet. The containers can be built from the same image. 

The deploy script can deploy both containers by separating container specific variable;

```
  docker run -d -t -i --name bridge_api_staging -p 3010:3010 \
  -e TARGET_ENV='linode-staging' \
  -e btcRpcUser=${BTC_RPC_USER} \
  -e btcRpcPwd=${BTC_RPC_PWD} \
  -e btcNode=${BTC_NODE} \
  -e mongoDbUrl=${MONGO_SBTC_URL} \
  -e mongoDbName=${MONGO_SBTC_DBNAME} \
  -e mongoUser=${MONGO_SBTC_USER} \
  -e mongoPwd=${MONGO_SBTC_PWD} \
  mijoco/bridge_api
```

This means we can have the testnet/mainnet containers running side by side on the same linode vm or GKE cluster;

![Screenshot 2023-04-19 at 13 17 37](https://user-images.githubusercontent.com/4384929/233149740-4ec4c7f9-e19a-471d-b55b-d37df90fe5cd.png)

with the upstream web server distinguishing by path;

![Screenshot 2023-04-19 at 13 18 49](https://user-images.githubusercontent.com/4384929/233149871-607c80df-dfea-4b84-9175-feb38bbf7307.png)

The sBTC bridge can then just target either container dynamically e.g.;

```
function addNetSelector (path:string) {
  if (CONFIG.VITE_NETWORK === 'testnet' || CONFIG.VITE_NETWORK === 'devnet') {
    return path.replace('bridge-api', 'bridge-api/testnet');
  }
  else {
    return path.replace('bridge-api', 'bridge-api/mainnet');
  }
}
```
