### ISSUE TITLE
As a user I want to spend the reclaim script path

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/sbtc-bridge-web#128]
See [Deposit Funds User Stories](https://brighton-blockchain.gitbook.io/sbtc-bridge/sbtc-bridge-plan/sbtc-bridge-user-stories/epic-deposit-funds#as-a-user-i-want-to-reclaim-my-funds) for details.

**Comment by igorsyl** [comment]
Feedback about _Deposit Funds User Stories_:

> sBTC is a SIP-010 fungible token
sBTC **enables** a SIP-010. sBTC as a Workgroup initiative has many more components besides the token.

> The sBTC Bridge is a trustless two-way mechanism that allows users to wrap and unwrap BTC as sBTC
The Bridge is not trustless. Stakeholders of the bridge place trust in the signers, the Stacks blockchain, Stacks block producers, and Bitcoin miners.

> The full specification of the sBTC protocol is SIP-021.
I would drop a link to the Master sBTC Design document, which is more up-to-date than the SIP: https://tmurl.net/master-sbtc-design

> Wrap bitcoin into sBTC tokens on the Stacks network. Unwrap your sBTC tokens back to bitcoin
The working group is revamping terminology regarding wrap/unwrap over the next couple of weeks.

Awesome GitBook!
