### ISSUE TITLE
Create typescript Bridge library

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/sbtc-bridge-web#133]
A library module is required for defining the types and functions common to both the Bridge web and API applications.

**Comment by igorsyl** [comment]
Need to coordinate work with @jferrant and @setbern

**Comment by radicleart** [comment]
The code is in this PR https://github.com/Trust-Machines/sbtc-bridge-api/pull/28

The lib is nested in /sbtc-bridge-lib still in draft / wip.
