### ISSUE TITLE
Create Dockerfile to run the front-end

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/sbtc-bridge-web#46]

**Comment by radicleart** [comment]
Fixed by [PR 93](https://github.com/Trust-Machines/sbtc-bridge-web/pull/93)

**Comment by radicleart** [comment]
Just realised this is the addition of express server to front end code. It's not really needed as the dev environment already has a server bundled. This dev server could be bundled inside docker but that's pretty unusual and would hinder front end front dev work.
