### ISSUE TITLE
The project should support multiple nets on one deployment.

### ISSUE THREAD

**Issue by sergey-shandar** [Trust-Machines/sbtc-bridge-web#80]
We can use a query parameter, for example `?net=main` or `?net=test`

**Comment by radicleart** [comment]
Could also be done in the web server config (Caddy/Nginx) to serve separate vhosts form filter on the URL. 

The only thing i want to avoid is to support two sets of env vars in the same js bundle as this messes up the code.

**Comment by friedger** [comment]
This is a standard retirement for all stacks projects.

Explorer is a good example. Let's do a standard component for it.

**Comment by igorsyl** [comment]
Mainnet available at https://sbtc.world
Agree both chain and api should use query params.
@radicleart needs to refactor chain and api env vars as query params.
@igorsyl & @sergey-shandar  can fix deployment.
