### ISSUE TITLE
Support SBTC Mini Peg In Time Lock Transactions

### ISSUE THREAD

**Issue by radicleart** [Trust-Machines/sbtc-bridge-web#81]
Wrap (Pegin) request transactions in Mini SBTC need to satisfy the requirement;

```
1. The user generates a taproot script that encodes this condition:  
“Here’s an 80-byte payload, but ignore it.  Next, if this transaction is 
mined in the last 144 Bitcoin blocks, then only the peg wallet signers 
can spend it.  Otherwise, only I can spend it.”
2. The user broadcasts a transaction with a single P2TR output that 
corresponds to the script generated in step 1.
```

at present the 80 byte payload is supported but not wrapped in a time lock money back guarantee style script.

**Comment by radicleart** [comment]
Adding some reference material on bitcoin time locks;

- https://github.com/bitcoin/bips/blob/master/bip-0112.mediawiki
- https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki
- https://medium.com/summa-technology/bitcoins-time-locks-27e0c362d7a1

**Comment by radicleart** [comment]
# PegIn Request Transaction

Some notes from a conversation yesterday. Two approaches laid out. 

Both based on using OP_DROP (user just sends bitcoin to a script hash address). Both enable the user to reclaim the funds if the sBTC mechanism breaks down for any reason - the user provides a `reclaim address` which can be different from the sending address they use to pegin. 

## 1. MultiSig Approach

The redeem script encodes the pegin data (an account or contract principal) and a 1 of 2 multisig script;

```
script1 = <data> OP_DROP OP_2 <pubkey1> <pubkey2> OP_1 OP_CHECKMULTISIG
```

This would be wrapped in a script hash say wsh as follows to generate the address the user pays to;

```
const pubkey1 = '03068ce1cb09d6c2e0cd08c8638b579fe2bf398d3341eb12c303da1b17dd9e34d1'
const pubkey2 = '02c0642636af6947dde337b1ea2bbe9cc142ec426ffac72ff73b7dc7afa99ac912'
const pmnt = btc.p2ms(1, [hex.decode(pubkey1), hex.decode(pubkey2)])
const wsh = {
	type: 'wsh',
	script: btc.Script.encode([data, 'DROP', pmnt.script])
}
const script = btc.p2wsh(wsh, this.net);
```

The two pubkeys belong to the user for reclaims and the sbtc wallet for minting sBTC respectively. Random pubkeys are chosen for example and beg the question where these come from in the application. The public key can't be derived from an address so if the user were pegging in from a Coinbase account with a clean address it's difficult to see how the this would be determined?

Some [discussion](https://bitcoin.stackexchange.com/questions/110091/why-does-the-locking-script-for-multsig-contain-pubkeys-instead-of-pubkeyhash) on pub key hashes in multi-sig.

```

## 2. Check Sequence Verify Approach

Note: this script is not tested but meant for illustration;

```
const wsh1 = {
	type: 'wsh',
	script: btc.Script.encode([data, 'DROP', 'IF', 144, 'CHECKSEQUENCEVERIFY', 'DROP', btc.OutScript.encode(btc.Address(this.net).decode(this.fromBtcAddress)), 'CHECKSIG', 'ELSE', 'DUP', 'HASH160', sbtcWalletUint8, 'EQUALVERIFY', 'CHECKSIG', 'ENDIF'])
}
const script = btc.p2wsh(wsh1, this.net);
```

The address revealed by the p2wsh payment is given to the user who sends their pegin tx - that transaction id is then broadcast to the signer binaries. The signers can spend the output within the first 144 blocks of it confirming. The user can reclaim it if they don't. 

The key difference is only the public key hash is required from the user which can be decoded from their from address.

**Comment by radicleart** [comment]
@igorsyl could the multisig version use pubkey hashes?

@netrome , @sergey-shandar tagging for help thinking this through !

**Comment by netrome** [comment]
A note here is that since we're using taproot, the 1 out of 2 condition should be encoded in a p2tr output and not a multisig script.

**Comment by radicleart** [comment]
See https://docs.google.com/document/d/1j2As89TI1crgtXV5D-OfQgYUhVC7C_ohVmgZoDogntQ/edit#heading=h.xzqvicpmkuvk for ongoing discussion.
